#
# Copyright (C) 2019 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

set -e

# Load extract_utils and do some sanity checks
MY_DIR="${BASH_SOURCE%/*}"
if [[ ! -d "$MY_DIR" ]]; then MY_DIR="$PWD"; fi

CM_ROOT="$MY_DIR"/../../..

HELPER="$CM_ROOT"/vendor/omni/build/tools/extract_utils.sh

if [ ! -f "$HELPER" ]; then
    echo "Unable to find helper script at $HELPER"
    exit 1
fi
. "$HELPER"

if [ -z "$1" ]; then
    echo "No input image supplied"
    exit 1
fi

if [ -z "$2" ]; then
    echo "No output filename supplied"
    exit 1
fi

VENDOR_SKIP_FILES_COMMON=(
    # Asus setenforce
    "bin/sar_setting"
    "bin/savelogs.sh"
    "bin/savelogmtp.sh"
    "bin/setenforce.sh"
    "bin/widevine.sh"

    # Audio
    "etc/a2dp_audio_policy_configuration.xml"
    "etc/default_volume_tables.xml"
    "etc/acdbdata/IDP_UPD/IDP_UPD_acdb_cal.acdb"
    "etc/acdbdata/IDP_UPD/IDP_UPD_workspaceFileXml.qwsp"
    "etc/acdbdata/IDP_UPD_diwali/IDP_UPD_diwali_acdb_cal.acdb"
    "etc/acdbdata/IDP_UPD_diwali/IDP_UPD_diwali_workspaceFileXml.qwsp"
    "etc/acdbdata/diwali_idp/IDP_diwali_acdb_cal.acdb"
    "etc/acdbdata/diwali_idp/IDP_diwali_workspaceFileXml.qwsp"
    "etc/acdbdata/diwali_idp_sku1/IDP_diwali_sku1_acdb_cal.acdb"
    "etc/acdbdata/diwali_idp_sku1/IDP_diwali_sku1_workspaceFileXml.qwsp"
    "etc/acdbdata/diwali_qrd/QRD_diwali_acdb_cal.acdb"
    "etc/acdbdata/diwali_qrd/QRD_diwali_workspaceFileXml.qwsp"
    "etc/acdbdata/diwali_qrd_sku1/QRD_diwali_sku1_acdb_cal.acdb"
    "etc/acdbdata/waipio_cdp/CDP_acdb_cal.acdb"
    "etc/acdbdata/waipio_cdp/CDP_workspaceFileXml.qwsp"
    "etc/acdbdata/waipio_mtp/MTP_acdb_cal.acdb"
    "etc/acdbdata/waipio_mtp/MTP_workspaceFileXml.qwsp"
    "etc/acdbdata/waipio_qrd/QRD_acdb_cal.acdb"
    "etc/acdbdata/waipio_qrd/QRD_workspaceFileXml.qwsp"
    "etc/audio/sku_cape/audio_effects.conf"
    "etc/audio/sku_cape/audio_effects.xml"
    "etc/audio/sku_cape/audio_policy_configuration.xml"
    "etc/audio/sku_cape/mixer_paths_waipio_cdp.xml"
    "etc/audio/sku_cape/mixer_paths_waipio_mtp.xml"
    "etc/audio/sku_cape/mixer_paths_waipio_qrd.xml"
    "etc/audio/sku_cape/resourcemanager_upd.xml"
    "etc/audio/sku_cape/resourcemanager_waipio_cdp.xml"
    "etc/audio/sku_cape/resourcemanager_waipio_mtp.xml"
    "etc/audio/sku_cape/resourcemanager_waipio_qrd.xml"
    "etc/audio/sku_cape_qssi/audio_policy_configuration.xml"
    "etc/audio/sku_diwali/audio_effects.conf"
    "etc/audio/sku_diwali/audio_effects.xml"
    "etc/audio/sku_diwali/audio_policy_configuration.xml"
    "etc/audio/sku_diwali/mixer_paths_diwali_idp.xml"
    "etc/audio/sku_diwali/mixer_paths_diwali_idp_sku1.xml"
    "etc/audio/sku_diwali/mixer_paths_diwali_qrd.xml"
    "etc/audio/sku_diwali/mixer_paths_diwali_qrd_sku1.xml"
    "etc/audio/sku_diwali/resourcemanager_diwali_idp.xml"
    "etc/audio/sku_diwali/resourcemanager_diwali_idp_sku1.xml"
    "etc/audio/sku_diwali/resourcemanager_diwali_qrd.xml"
    "etc/audio/sku_diwali/resourcemanager_diwali_qrd_sku1.xml"
    "etc/audio/sku_diwali/resourcemanager_upd.xml"
    "etc/audio/sku_diwali_qssi/audio_policy_configuration.xml"
    "etc/audio/sku_taro/audio_effects.conf"
    "etc/audio/sku_taro/audio_effects.xml"
    "etc/audio/sku_taro/audio_policy_configuration.xml"
    "etc/audio/sku_taro/mixer_paths_waipio_cdp.xml"
    "etc/audio/sku_taro/mixer_paths_waipio_mtp.xml"
    "etc/audio/sku_taro/mixer_paths_waipio_qrd.xml"
    "etc/audio/sku_taro/resourcemanager_upd.xml"
    "etc/audio/sku_taro/resourcemanager_waipio_cdp.xml"
    "etc/audio/sku_taro/resourcemanager_waipio_mtp.xml"
    "etc/audio/sku_taro/resourcemanager_waipio_qrd.xml"
    "etc/audio/sku_taro_qssi/audio_policy_configuration.xml"
    "etc/audio/DAVINCI/audio_policy_configuration_AI2202.xml"
    "etc/audio/DAVINCI/audio_policy_volumes_AI2202.xml"
    "etc/audio_effects.conf"
    "etc/audio_effects.xml"
    "etc/audio_io_policy.conf"
    "etc/audio_platform_info.xml"
    "etc/audio_platform_info_hdk.xml"
    "etc/audio_platform_info_intcodec.xml"
    "etc/audio_platform_info_qrd.xml"
    "etc/audio_policy_configuration.xml"
    "etc/audio_policy_volumes.xml"
    "etc/bluetooth_qti_audio_policy_configuration.xml"
    "etc/bluetooth_qti_hearing_aid_audio_policy_configuration.xml"
    "bin/hw/android.hardware.audio.service"
    "etc/init/android.hardware.audio.service.rc"
    "lib/android.hardware.audio.common-util.so"
    "lib/android.hardware.audio.common@2.0-util.so"
    "lib/android.hardware.audio.common@4.0-util.so"
    "lib/android.hardware.audio.common@5.0-util.so"
    "lib/android.hardware.audio.common@6.0-util.so"
    "lib/hw/android.hardware.audio.effect@2.0-impl.so"
    "lib/hw/android.hardware.audio.effect@4.0-impl.so"
    "lib/hw/android.hardware.audio.effect@5.0-impl.so"
    "lib/hw/android.hardware.audio.effect@6.0-impl.so"
    "lib/hw/android.hardware.audio@2.0-impl.so"
    "lib/hw/android.hardware.audio@4.0-impl.so"
    "lib/hw/android.hardware.audio@5.0-impl.so"
    "lib/hw/android.hardware.audio@6.0-impl.so"
    "lib64/android.hardware.audio.common-util.so"
    "lib64/android.hardware.audio.common@2.0-util.so"
    "lib64/android.hardware.audio.common@4.0-util.so"
    "lib64/android.hardware.audio.common@5.0-util.so"
    "lib64/android.hardware.audio.common@6.0-util.so"
    "lib64/hw/android.hardware.audio.effect@2.0-impl.so"
    "lib64/hw/android.hardware.audio.effect@4.0-impl.so"
    "lib64/hw/android.hardware.audio.effect@5.0-impl.so"
    "lib64/hw/android.hardware.audio.effect@6.0-impl.so"
    "lib64/hw/android.hardware.audio@2.0-impl.so"
    "lib64/hw/android.hardware.audio@4.0-impl.so"
    "lib64/hw/android.hardware.audio@5.0-impl.so"
    "lib64/hw/android.hardware.audio@6.0-impl.so"
    "lib/android.hardware.audio.common@4.0.so"
    "lib/android.hardware.audio.common@5.0.so"
    "lib/android.hardware.audio.common@6.0.so"
    "lib/android.hardware.audio.common@7.0-enums.so"
    "lib/android.hardware.audio.common@7.0-util.so"
    "lib/android.hardware.audio.common@7.0.so"
    "lib/android.hardware.audio.effect@2.0-util.so"
    "lib/android.hardware.audio.effect@2.0.so"
    "lib/android.hardware.audio.effect@4.0-util.so"
    "lib/android.hardware.audio.effect@4.0.so"
    "lib/android.hardware.audio.effect@5.0-util.so"
    "lib/android.hardware.audio.effect@5.0.so"
    "lib/android.hardware.audio.effect@6.0-util.so"
    "lib/android.hardware.audio.effect@6.0.so"
    "lib/android.hardware.audio.effect@7.0-util.so"
    "lib/android.hardware.audio.effect@7.0.so"
    "lib/android.hardware.audio@2.0-util.so"
    "lib/android.hardware.audio@2.0.so"
    "lib/android.hardware.audio@4.0-util.so"
    "lib/android.hardware.audio@4.0.so"
    "lib/android.hardware.audio@5.0-util.so"
    "lib/android.hardware.audio@5.0.so"
    "lib/android.hardware.audio@6.0-util.so"
    "lib/android.hardware.audio@6.0.so"
    "lib/android.hardware.audio@7.0-util.so"
    "lib/android.hardware.audio@7.0.so"
    "lib/hw/android.hardware.audio.effect@7.0-impl.so"
    "lib/hw/android.hardware.audio@7.0-impl.so"
    "lib64/android.hardware.audio.common@4.0.so"
    "lib64/android.hardware.audio.common@5.0.so"
    "lib64/android.hardware.audio.common@6.0.so"
    "lib64/android.hardware.audio.common@7.0-enums.so"
    "lib64/android.hardware.audio.common@7.0-util.so"
    "lib64/android.hardware.audio.common@7.0.so"
    "lib64/android.hardware.audio.effect@2.0-util.so"
    "lib64/android.hardware.audio.effect@2.0.so"
    "lib64/android.hardware.audio.effect@4.0-util.so"
    "lib64/android.hardware.audio.effect@4.0.so"
    "lib64/android.hardware.audio.effect@5.0-util.so"
    "lib64/android.hardware.audio.effect@5.0.so"
    "lib64/android.hardware.audio.effect@6.0-util.so"
    "lib64/android.hardware.audio.effect@6.0.so"
    "lib64/android.hardware.audio.effect@7.0-util.so"
    "lib64/android.hardware.audio.effect@7.0.so"
    "lib64/android.hardware.audio@2.0-util.so"
    "lib64/android.hardware.audio@2.0.so"
    "lib64/android.hardware.audio@4.0-util.so"
    "lib64/android.hardware.audio@4.0.so"
    "lib64/android.hardware.audio@5.0-util.so"
    "lib64/android.hardware.audio@5.0.so"
    "lib64/android.hardware.audio@6.0-util.so"
    "lib64/android.hardware.audio@6.0.so"
    "lib64/android.hardware.audio@7.0-util.so"
    "lib64/android.hardware.audio@7.0.so"
    "lib64/hw/android.hardware.audio.effect@7.0-impl.so"
    "lib64/hw/android.hardware.audio@7.0-impl.so"
    "lib/hw/audio.primary.default.so"
    "lib64/hw/audio.primary.default.so"
    "lib/libeffects.so"
    "lib/libeffectsconfig.so"
    "lib64/libeffects.so"
    "lib64/libeffectsconfig.so"
    "lib/libnbaio_mono.so"
    "lib64/libnbaio_mono.so"

    # Binary
    "bin/acpi"
    "bin/applypatch"
    "bin/asus_mediaflag.sh"
    "bin/base64"
    "bin/basename"
    "bin/boringssl_self_test32"
    "bin/boringssl_self_test64"
    "bin/btnvtool"
    "bin/blockdev"
    "bin/cal"
    "bin/cat"
    "bin/chattr"
    "bin/chcon"
    "bin/checkpoint_gc"
    "bin/chgrp"
    "bin/chmod"
    "bin/chown"
    "bin/chroot"
    "bin/chrt"
    "bin/cksum"
    "bin/clear"
    "bin/cmp"
    "bin/comm"
    "bin/cp"
    "bin/cpio"
    "bin/cut"
    "bin/country.sh"
    "bin/cplay"
    "bin/csc/erase_batinfo.sh"
    "bin/csc/restore_batinfo.sh"
    "bin/cscclearlog.sh"
    "bin/ddr_info.sh"
    "bin/debug-diag"
    "bin/date"
    "bin/dd"
    "bin/df"
    "bin/diff"
    "bin/dirname"
    "bin/devmem"
    "bin/dmesg"
    "bin/dos2unix"
    "bin/du"
    "bin/echo"
    "bin/egrep"
    "bin/env"
    "bin/expand"
    "bin/expr"
    "bin/fallocate"
    "bin/false"
    "bin/fastrpc_tests_apps"
    "bin/fastrpc_tests_apps32"
    "bin/firmware_version.sh"
    "bin/fgrep"
    "bin/file"
    "bin/find"
    "bin/flock"
    "bin/fmt"
    "bin/free"
    "bin/fsync"
    "bin/getconf"
    "bin/getenforce"
    "bin/getevent"
    "bin/getprop"
    "bin/groups"
    "bin/gunzip"
    "bin/gzip"
    "bin/head"
    "bin/hostname"
    "bin/hwclock"
    "bin/i2cdetect"
    "bin/i2cdump"
    "bin/i2cget"
    "bin/i2cset"
    "bin/iconv"
    "bin/id"
    "bin/ifconfig"
    "bin/inotifyd"
    "bin/insmod"
    "bin/install"
    "bin/install_key_server"
    "bin/ionice"
    "bin/iorenice"
    "bin/irsc_util"
    "bin/is_hdcp_valid"
    "bin/is_keybox_valid"
    "bin/is_keymaster_valid"
    "bin/kill"
    "bin/killall"
    "bin/ln"
    "bin/load_policy"
    "bin/log"
    "bin/logname"
    "bin/losetup"
    "bin/ls"
    "bin/lsattr"
    "bin/lsmod"
    "bin/lsof"
    "bin/lspci"
    "bin/lsusb"
    "bin/md5sum"
    "bin/microcom"
    "bin/mkdir"
    "bin/mkfifo"
    "bin/mknod"
    "bin/mkswap"
    "bin/mktemp"
    "bin/modinfo"
    "bin/modprobe"
    "bin/more"
    "bin/mount"
    "bin/mountpoint"
    "bin/mv"
    "bin/nc"
    "bin/netcat"
    "bin/netstat"
    "bin/newfs_msdos"
    "bin/nice"
    "bin/nl"
    "bin/nohup"
    "bin/nproc"
    "bin/nsenter"
    "bin/od"
    "bin/paste"
    "bin/patch"
    "bin/pgrep"
    "bin/pidof"
    "bin/pkill"
    "bin/pmap"
    "bin/prepare_asusdebug.sh"
    "bin/printenv"
    "bin/printf"
    "bin/ps"
    "bin/pwd"
    "bin/qmi-framework-tests/qmi_test_mt_client_init_instance"
    "bin/readlink"
    "bin/readelf"
    "bin/realpath"
    "bin/renice"
    "bin/restorecon"
    "bin/rm"
    "bin/rmdir"
    "bin/rmmod"
    "bin/runcon"
    "bin/sed"
    "bin/sendevent"
    "bin/seq"
    "bin/setenforce"
    "bin/setprop"
    "bin/setsid"
    "bin/sha1sum"
    "bin/sha224sum"
    "bin/sha256sum"
    "bin/sha384sum"
    "bin/sha512sum"
    "bin/sleep"
    "bin/sort"
    "bin/split"
    "bin/start"
    "bin/stat"
    "bin/stop"
    "bin/strings"
    "bin/stty"
    "bin/swapoff"
    "bin/swapon"
    "bin/sync"
    "bin/sysctl"
    "bin/tac"
    "bin/tail"
    "bin/tar"
    "bin/taskset"
    "bin/tee"
    "bin/test"
    "bin/test_BinMerge"
    "bin/test_DualCamQcomAECali"
    "bin/test_ShadingCaliForQcom"
    "bin/test_aeCali"
    "bin/test_afCaliDB"
    "bin/test_chkCali"
    "bin/test_diag"
    "bin/test_genCali"
    "bin/test_qafCali"
    "bin/testapp_diag_senddata"
    "bin/time"
    "bin/timeout"
    "bin/top"
    "bin/touch"
    "bin/touch_ver.sh"
    "bin/tr"
    "bin/true"
    "bin/truncate"
    "bin/tty"
    "bin/ulimit"
    "bin/umount"
    "bin/uname"
    "bin/uniq"
    "bin/unix2dos"
    "bin/unlink"
    "bin/unshare"
    "bin/uptime"
    "bin/usleep"
    "bin/uudecode"
    "bin/uuencode"
    "bin/uuidgen"
    "bin/UTSdumpstate.sh"
    "bin/UpdateAttestationKey"
    "bin/UpdateDeviceName"
    "bin/ubwcconvert"
    "bin/ufs_info.sh"
    "bin/vmstat"
    "bin/watch"
    "bin/wc"
    "bin/which"
    "bin/whoami"
    "bin/WifiAntenna.sh"
    "bin/WifiMac.sh"
    "bin/WifiSARPower.sh"
    "bin/xargs"
    "bin/xxd"
    "bin/yes"
    "bin/zcat"

    # Biometrics
    "bin/hw/android.hardware.biometrics.face@1.0-service.face"
    "etc/init/android.hardware.biometrics.face@1.0-service.face.rc"
    "lib64/android.hardware.biometrics.face-V1-ndk_platform.so"
    "bin/hw/android.hardware.biometrics.fingerprint@2.1-service"
    "etc/init/android.hardware.biometrics.fingerprint@2.1-service.rc"
    "etc/vintf/manifest/android.hardware.biometrics.fingerprint@2.1-service.xml"
    "lib64/android.hardware.biometrics.common-V1-ndk_platform.so"
    "lib64/android.hardware.biometrics.fingerprint@2.1.so"

    # Bootctrl
    "lib/hw/android.hardware.boot@1.0-impl-1.2-qti.so"
    "lib/libboot_control_qti.so"
    "lib64/hw/android.hardware.boot@1.0-impl-1.2-qti.so"
    "lib64/libboot_control_qti.so"
    "bin/hw/android.hardware.boot@1.2-service"
    "etc/init/android.hardware.boot@1.2-service.rc"
    "etc/vintf/manifest/android.hardware.boot@1.2.xml"

    # build.prop for Region specific
    "build_EU.prop"
    "build_EU_2.prop"
    "build_FR.prop"
    "build_JP.prop"
    "build_QC.prop"
    "build_RU.prop"
    "build_TW.prop"
    "build_TW_1.prop"
    "build_TW_2.prop"
    "odm_dlkm/etc/NOTICE.xml.gz"
    "odm_dlkm/etc/build.prop"

    # Camera
    "etc/camera/camxoverridesettings.txt"

    # config.fs
    "etc/fs_config_dirs"
    "etc/fs_config_files"
    "etc/group"
    "etc/passwd"

    # Display
    "lib/libqdMetaData.so"
    "lib64/libqdMetaData.so"
    "lib/libgralloc.qti.so"
    "lib64/libgralloc.qti.so"
    "lib/libdisplayconfig.qti.so"
    "lib64/libdisplayconfig.qti.so"
    "lib/libdisplaydebug.so"
    "lib64/libdisplaydebug.so"
    "lib/vendor.display.config@1.0.so"
    "lib/vendor.display.config@1.1.so"
    "lib/vendor.display.config@1.10.so"
    "lib/vendor.display.config@1.11.so"
    "lib/vendor.display.config@1.12.so"
    "lib/vendor.display.config@1.13.so"
    "lib/vendor.display.config@1.14.so"
    "lib/vendor.display.config@1.15.so"
    "lib/vendor.display.config@1.2.so"
    "lib/vendor.display.config@1.3.so"
    "lib/vendor.display.config@1.4.so"
    "lib/vendor.display.config@1.5.so"
    "lib/vendor.display.config@1.6.so"
    "lib/vendor.display.config@1.7.so"
    "lib/vendor.display.config@1.8.so"
    "lib/vendor.display.config@1.9.so"
    "lib/vendor.display.config@2.0.so"
    "lib64/vendor.display.config@1.0.so"
    "lib64/vendor.display.config@1.1.so"
    "lib64/vendor.display.config@1.10.so"
    "lib64/vendor.display.config@1.11.so"
    "lib64/vendor.display.config@1.12.so"
    "lib64/vendor.display.config@1.13.so"
    "lib64/vendor.display.config@1.14.so"
    "lib64/vendor.display.config@1.15.so"
    "lib64/vendor.display.config@1.2.so"
    "lib64/vendor.display.config@1.3.so"
    "lib64/vendor.display.config@1.4.so"
    "lib64/vendor.display.config@1.5.so"
    "lib64/vendor.display.config@1.6.so"
    "lib64/vendor.display.config@1.7.so"
    "lib64/vendor.display.config@1.8.so"
    "lib64/vendor.display.config@1.9.so"
    "lib64/vendor.display.config@2.0.so"
    "lib/hw/android.hardware.graphics.mapper@4.0-impl-qti-display.so"
    "lib64/hw/android.hardware.graphics.mapper@4.0-impl-qti-display.so"
    "lib/vendor.qti.hardware.display.allocator@1.0.so"
    "lib/vendor.qti.hardware.display.allocator@3.0.so"
    "lib/vendor.qti.hardware.display.allocator@4.0.so"
    "lib/vendor.qti.hardware.display.composer@1.0.so"
    "lib/vendor.qti.hardware.display.composer@2.0.so"
    "lib/vendor.qti.hardware.display.config-V1-ndk_platform.so"
    "lib/vendor.qti.hardware.display.config-V2-ndk_platform.so"
    "lib/vendor.qti.hardware.display.config-V3-ndk_platform.so"
    "lib/vendor.qti.hardware.display.config-V4-ndk_platform.so"
    "lib/vendor.qti.hardware.display.config-V5-ndk_platform.so"
    "lib/vendor.qti.hardware.display.config-V6-ndk_platform.so"
    "lib/vendor.qti.hardware.display.demura@2.0.so"
    "lib/vendor.qti.hardware.display.mapper@1.0.so"
    "lib/vendor.qti.hardware.display.mapper@1.1.so"
    "lib/vendor.qti.hardware.display.mapper@2.0.so"
    "lib/vendor.qti.hardware.display.mapper@3.0.so"
    "lib/vendor.qti.hardware.display.mapper@4.0.so"
    "lib/vendor.qti.hardware.display.mapperextensions@1.0.so"
    "lib/vendor.qti.hardware.display.mapperextensions@1.1.so"
    "lib/vendor.qti.hardware.display.mapperextensions@1.2.so"
    "lib64/vendor.qti.hardware.display.allocator@1.0.so"
    "lib64/vendor.qti.hardware.display.allocator@3.0.so"
    "lib64/vendor.qti.hardware.display.allocator@4.0.so"
    "lib64/vendor.qti.hardware.display.composer@1.0.so"
    "lib64/vendor.qti.hardware.display.composer@2.0.so"
    "lib64/vendor.qti.hardware.display.composer@3.0.so"
    "lib64/vendor.qti.hardware.display.composer@3.1.so"
    "lib64/vendor.qti.hardware.display.config-V1-ndk_platform.so"
    "lib64/vendor.qti.hardware.display.config-V2-ndk_platform.so"
    "lib64/vendor.qti.hardware.display.config-V3-ndk_platform.so"
    "lib64/vendor.qti.hardware.display.config-V4-ndk_platform.so"
    "lib64/vendor.qti.hardware.display.config-V5-ndk_platform.so"
    "lib64/vendor.qti.hardware.display.config-V6-ndk_platform.so"
    "lib64/vendor.qti.hardware.display.demura@2.0.so"
    "lib64/vendor.qti.hardware.display.mapper@1.0.so"
    "lib64/vendor.qti.hardware.display.mapper@1.1.so"
    "lib64/vendor.qti.hardware.display.mapper@2.0.so"
    "lib64/vendor.qti.hardware.display.mapper@3.0.so"
    "lib64/vendor.qti.hardware.display.mapper@4.0.so"
    "lib64/vendor.qti.hardware.display.mapperextensions@1.0.so"
    "lib64/vendor.qti.hardware.display.mapperextensions@1.1.so"
    "lib64/vendor.qti.hardware.display.mapperextensions@1.2.so"
    "bin/hw/vendor.qti.hardware.display.allocator-service"
    "bin/hw/vendor.qti.hardware.display.demura-service"
    "etc/init/vendor.qti.hardware.display.allocator-service.rc"
    "etc/init/vendor.qti.hardware.display.demura-service.rc"
    "etc/vintf/manifest/android.hardware.graphics.mapper-impl-qti-display.xml"
    "etc/vintf/manifest/vendor.qti.hardware.display.allocator-service.xml"
    "etc/vintf/manifest/vendor.qti.hardware.display.demura-service.xml"
    "bin/init.qti.display_boot.sh"
    "etc/init/init.qti.display_boot.rc"
    "lib/hw/gralloc.default.so"
    "lib64/hw/gralloc.default.so"
    "lib/libgralloccore.so"
    "lib/libgrallocutils.so"
    "lib64/libgralloccore.so"
    "lib64/libgrallocutils.so"
    "lib/libqdutils.so"
    "lib64/libqdutils.so"
    "lib/libdrm.so"
    "lib/libdrmutils.so"
    "lib64/libdrm.so"
    "lib64/libdrmutils.so"
    "lib/libgpu_tonemapper.so"
    "lib64/libgpu_tonemapper.so"
    "lib64/libhistogram.so"
    "lib/libqservice.so"
    "lib64/libqservice.so"
    "lib/libfilefinder.so"
    "lib64/libfilefinder.so"
    "bin/hw/vendor.qti.hardware.display.composer-service"
    "etc/init/vendor.qti.hardware.display.composer-service.rc"
    "etc/vintf/manifest/vendor.qti.hardware.display.composer-service.xml"
    "lib/libsdedrm.so"
    "lib/libsdmcore.so"
    "lib/libsdmutils.so"
    "lib64/libsdedrm.so"
    "lib64/libsdmcore.so"
    "lib64/libsdmutils.so"
    "lib/libsdmextension.so"
    "lib64/libsdmextension.so" #moved to proprietary-files.txt to pin it

    # Display (PixelWorks)
    "bin/hw/vendor.pixelworks.hardware.display.iris-service"
    "bin/hw/vendor.pixelworks.hardware.feature.irisfeature-service"
    "etc/init/vendor.pixelworks.hardware.display.iris-service.rc"
    "etc/init/vendor.pixelworks.hardware.feature.irisfeature-service.rc"
    "etc/vintf/manifest/vendor.pixelworks.hardware.display.iris-service.xml"
    "etc/vintf/manifest/vendor.pixelworks.hardware.feature.irisfeature-service.xml"
    "lib/vendor.pixelworks.hardware.display@1.0.so"
    "lib/vendor.pixelworks.hardware.display@1.1.so"
    "lib/vendor.pixelworks.hardware.feature@1.0.so"
    "lib64/vendor.pixelworks.hardware.display@1.0.so"
    "lib64/vendor.pixelworks.hardware.display@1.1.so"
    "lib64/vendor.pixelworks.hardware.feature@1.0.so"
    "bin/irisConfig"
    "etc/inparm/irissoft/inparm_ai2201_mp/ModifyHistory.txt"
    "etc/inparm/irissoft/inparm_ai2201_mp/inParm.lst"
    "etc/inparm/irissoft/inparm_ai2201_mp/inParm1.txt"
    "etc/inparm/irissoft/inparm_ai2201_mp/inParm10.txt"
    "etc/inparm/irissoft/inparm_ai2201_mp/inParm11.txt"
    "etc/inparm/irissoft/inparm_ai2201_mp/inParm12.txt"
    "etc/inparm/irissoft/inparm_ai2201_mp/inParm13.txt"
    "etc/inparm/irissoft/inparm_ai2201_mp/inParm14.txt"
    "etc/inparm/irissoft/inparm_ai2201_mp/inParm15.txt"
    "etc/inparm/irissoft/inparm_ai2201_mp/inParm16.txt"
    "etc/inparm/irissoft/inparm_ai2201_mp/inParm17.txt"
    "etc/inparm/irissoft/inparm_ai2201_mp/inParm18.txt"
    "etc/inparm/irissoft/inparm_ai2201_mp/inParm19.txt"
    "etc/inparm/irissoft/inparm_ai2201_mp/inParm2.txt"
    "etc/inparm/irissoft/inparm_ai2201_mp/inParm20.txt"
    "etc/inparm/irissoft/inparm_ai2201_mp/inParm21.txt"
    "etc/inparm/irissoft/inparm_ai2201_mp/inParm22.txt"
    "etc/inparm/irissoft/inparm_ai2201_mp/inParm23.txt"
    "etc/inparm/irissoft/inparm_ai2201_mp/inParm24.txt"
    "etc/inparm/irissoft/inparm_ai2201_mp/inParm25.txt"
    "etc/inparm/irissoft/inparm_ai2201_mp/inParm26.txt"
    "etc/inparm/irissoft/inparm_ai2201_mp/inParm27.txt"
    "etc/inparm/irissoft/inparm_ai2201_mp/inParm28.txt"
    "etc/inparm/irissoft/inparm_ai2201_mp/inParm29.txt"
    "etc/inparm/irissoft/inparm_ai2201_mp/inParm3.txt"
    "etc/inparm/irissoft/inparm_ai2201_mp/inParm30.txt"
    "etc/inparm/irissoft/inparm_ai2201_mp/inParm31.txt"
    "etc/inparm/irissoft/inparm_ai2201_mp/inParm32.txt"
    "etc/inparm/irissoft/inparm_ai2201_mp/inParm33.txt"
    "etc/inparm/irissoft/inparm_ai2201_mp/inParm34.txt"
    "etc/inparm/irissoft/inparm_ai2201_mp/inParm35.txt"
    "etc/inparm/irissoft/inparm_ai2201_mp/inParm36.txt"
    "etc/inparm/irissoft/inparm_ai2201_mp/inParm37.txt"
    "etc/inparm/irissoft/inparm_ai2201_mp/inParm38.txt"
    "etc/inparm/irissoft/inparm_ai2201_mp/inParm39.txt"
    "etc/inparm/irissoft/inparm_ai2201_mp/inParm4.txt"
    "etc/inparm/irissoft/inparm_ai2201_mp/inParm5.txt"
    "etc/inparm/irissoft/inparm_ai2201_mp/inParm6.txt"
    "etc/inparm/irissoft/inparm_ai2201_mp/inParm7.txt"
    "etc/inparm/irissoft/inparm_ai2201_mp/inParm8.txt"
    "etc/inparm/irissoft/inparm_ai2201_mp/inParm9.txt"
    "etc/inparm/irissoft/inparm_ai2201_mp/mcfCheck.txt"
    "etc/inparm/irissoft/inparm_ai2201_mp/mcfCheck_low.txt"
    "etc/inparm/irissoft/inparm_ai2202_mp/Release.txt"
    "etc/inparm/irissoft/inparm_ai2202_mp/inParm.lst"
    "etc/inparm/irissoft/inparm_ai2202_mp/inParm1.txt"
    "etc/inparm/irissoft/inparm_ai2202_mp/inParm10.txt"
    "etc/inparm/irissoft/inparm_ai2202_mp/inParm11.txt"
    "etc/inparm/irissoft/inparm_ai2202_mp/inParm12.txt"
    "etc/inparm/irissoft/inparm_ai2202_mp/inParm13.txt"
    "etc/inparm/irissoft/inparm_ai2202_mp/inParm14.txt"
    "etc/inparm/irissoft/inparm_ai2202_mp/inParm15.txt"
    "etc/inparm/irissoft/inparm_ai2202_mp/inParm16.txt"
    "etc/inparm/irissoft/inparm_ai2202_mp/inParm17.txt"
    "etc/inparm/irissoft/inparm_ai2202_mp/inParm18.txt"
    "etc/inparm/irissoft/inparm_ai2202_mp/inParm2.txt"
    "etc/inparm/irissoft/inparm_ai2202_mp/inParm3.txt"
    "etc/inparm/irissoft/inparm_ai2202_mp/inParm4.txt"
    "etc/inparm/irissoft/inparm_ai2202_mp/inParm5.txt"
    "etc/inparm/irissoft/inparm_ai2202_mp/inParm6.txt"
    "etc/inparm/irissoft/inparm_ai2202_mp/inParm7.txt"
    "etc/inparm/irissoft/inparm_ai2202_mp/inParm8.txt"
    "etc/inparm/irissoft/inparm_ai2202_mp/inParm9.txt"
    "etc/inparm/irissoft/inparm_ai2202_mp/mcfCheck.txt"
    "etc/inparm/irissoft/inparm_ai2202_mp/mcfCheck_low.txt"
    "etc/iris_configs.xml"
    "etc/irissoft_ASUS_ams592YP01_cmd_mode_dsc_fhd_plus_panel.dat"
    "etc/irissoft_ASUS_ams592YP01_cmd_mode_dsc_fhd_plus_panel.xml"
    "etc/irissoft_ASUS_ams678_er2_cmd_mode_dsc_fhd_plus_panel.dat"
    "etc/irissoft_ASUS_ams678_er2_cmd_mode_dsc_fhd_plus_panel.xml"
    "etc/irissoft_ai2201.fw"
    "lib/libpwirisIoctlWrapper.so"
    "lib/libpwirisPCS.so"
    "lib/libpwiriscalibrate.so"
    "lib/libpwirisfeature.so"
    "lib/libpwirishalwrapper.so"
    "lib/libpwirispq.so"
    "lib/libpwirisservice.so"
    "lib/libpwirissoft.so"
    "lib/libpwsoftirisPCS.so"
    "lib64/libpwirisIoctlWrapper.so"
    "lib64/libpwirisPCS.so"
    "lib64/libpwiriscalibrate.so"
    "lib64/libpwirisfeature.so"
    "lib64/libpwirishalwrapper.so"
    "lib64/libpwirispq.so"
    "lib64/libpwirisservice.so"
    "lib64/libpwirissoft.so"
    "lib64/libpwsoftirisPCS.so"

    # fstab
    "etc/fstab.qcom"

    # Init Scripts
    "bin/init.asus.changebinder.sh"
    "bin/init.asus.check_asdf.sh"
    "bin/init.asus.check_last.sh"
    "bin/init.asus.ramdump.sh"
    "bin/init.kernel.post_boot-shima.sh"
    "bin/init.kernel.post_boot-yupik.sh"
    "bin/init.qti.kernel.debug-lahaina.sh"
    "bin/init.qti.kernel.debug-shima.sh"
    "bin/init.qti.kernel.debug-yupik.sh"
    "bin/init.qti.kernel.debug.sh"
    "etc/init/init.asus.demoapp.rc"
    "etc/init/init.asus.osinfo.rc"
    "etc/init/hw/init.asus.rc"
    "etc/init/hw/init.asus.debugtool.rc"
    "etc/init/hw/init.qcom.rc"
    "etc/init/hw/init.target.rc"

    # Launcher
    "etc/workspace_grid_setting.xml"
    "etc/Generic/Launcher/default_workspace/default_allapp.xml"
    "etc/Generic/Launcher/default_workspace/phone_workspace.xml"
    "etc/ID/ASUS/Launcher/default_workspace/default_allapp.xml"
    "etc/ID/ASUS/Launcher/default_workspace/phone_workspace.xml"
    "etc/JP/ACJ/Launcher/default_workspace/default_allapp.xml"
    "etc/JP/ACJ/Launcher/default_workspace/phone_workspace.xml"
    "etc/JP/ASUS/Launcher/default_workspace/default_allapp.xml"
    "etc/JP/ASUS/Launcher/default_workspace/phone_workspace.xml"
    "etc/RU/ASUS/Launcher/default_workspace/default_allapp.xml"
    "etc/RU/ASUS/Launcher/default_workspace/phone_workspace.xml"
    "etc/TW/APTG/Launcher/default_workspace/default_allapp.xml"
    "etc/TW/APTG/Launcher/default_workspace/phone_workspace.xml"
    "etc/TW/ASUS/Launcher/default_workspace/default_allapp.xml"
    "etc/TW/ASUS/Launcher/default_workspace/phone_workspace.xml"
    "etc/US/ASUS/Launcher/default_workspace/default_allapp.xml"
    "etc/US/ASUS/Launcher/default_workspace/phone_workspace.xml"
    "etc/WW/ASUS/Launcher/default_workspace/default_allapp.xml"
    "etc/WW/ASUS/Launcher/default_workspace/phone_workspace.xml"

    # Light
    "bin/hw/android.hardware.lights-service.qti"
    "etc/init/android.hardware.lights-qti.rc"
    "etc/vintf/manifest/android.hardware.lights-qti.xml"
    "bin/hw/vendor.qti.hardware.lights.service"
    "etc/init/vendor.qti.hardware.lights.service.rc"
    "etc/vintf/manifest/vendor.qti.hardware.lights.service.xml"

    # Logs
    "bin/ASUSEvtlog"
    "etc/init/ASUSEvtlog.rc"
    "bin/asuslogcat"
    "bin/init.asus.checkdatalog.sh"
    "bin/init.asus.checklogsize.sh"
    "bin/init.asus.kernelmessage.sh"
    "bin/init.asus.zram.sh"
    "bin/PhoneInfoTest"
    "bin/vendor_savelogs.sh"

    # Manifest
    "etc/vintf/manifest_cape.xml"
    "etc/vintf/manifest_diwali.xml"
    "etc/vintf/manifest_taro.xml"

    # Media
    "etc/media_codecs_google_audio.xml"
    "etc/media_codecs_google_c2.xml"
    "etc/media_codecs_google_c2_audio.xml"
    "etc/media_codecs_google_c2_video.xml"
    "etc/media_codecs_google_telephony.xml"
    "etc/media_codecs_google_video.xml"
    "etc/media_codecs_google_video_le.xml"
    "bin/hw/android.hardware.cas@1.2-service"
    "etc/init/android.hardware.cas@1.2-service.rc"
    "etc/vintf/manifest/android.hardware.cas@1.2-service.xml"
    "lib/libstagefrighthw.so"
    "lib/vndk/libstagefright_foundation.so"
    "lib/vndk/libstagefright_omx.so"
    "lib64/libstagefright_bufferpool@2.0.1.so"
    "lib64/libstagefright_soft_qtiflacdec.so"
    "lib64/libstagefright_softomx.so"
    "lib64/libstagefrighthw.so"
    "lib/libOmxCore.so"
    "lib64/libOmxCore.so"
    "lib/libmm-omxcore.so"
    "lib64/libmm-omxcore.so"
    "lib/libplatformconfig.so"
    "lib64/libplatformconfig.so"
    "lib/libcodec2_vndk.so"
    "lib64/libcodec2_vndk.so"
    "lib/libcodec2_hidl@1.0.so"
    "lib/libcodec2_hidl_plugin.so"
    "lib64/libcodec2_hidl@1.0.so"
    "lib64/libcodec2_hidl_plugin.so"
    "lib/libstagefright_softomx.so"
    "lib/libstagefright_softomx_plugin.so"
    "lib/libstagefright_amrnb_common.so"
    "lib/libstagefright_bufferpool@2.0.1.so"
    "lib/libstagefright_enc_common.so"
    "lib/libstagefright_flacdec.so"
    "lib/libstagefright_soft_aacdec.so"
    "lib/libstagefright_soft_aacenc.so"
    "lib/libstagefright_soft_amrdec.so"
    "lib/libstagefright_soft_amrnbenc.so"
    "lib/libstagefright_soft_amrwbenc.so"
    "lib/libstagefright_soft_avcdec.so"
    "lib/libstagefright_soft_avcenc.so"
    "lib/libstagefright_soft_flacdec.so"
    "lib/libstagefright_soft_flacenc.so"
    "lib/libstagefright_soft_g711dec.so"
    "lib/libstagefright_soft_gsmdec.so"
    "lib/libstagefright_soft_hevcdec.so"
    "lib/libstagefright_soft_mp3dec.so"
    "lib/libstagefright_soft_mpeg2dec.so"
    "lib/libstagefright_soft_mpeg4dec.so"
    "lib/libstagefright_soft_mpeg4enc.so"
    "lib/libstagefright_soft_opusdec.so"
    "lib/libstagefright_soft_rawdec.so"
    "lib/libstagefright_soft_vorbisdec.so"
    "lib/libstagefright_soft_vpxdec.so"
    "lib/libstagefright_soft_vpxenc.so"

    # Other services
    "bin/asus_osinfo"
    "bin/hw/android.hardware.atrace@1.0-service"
    "etc/init/android.hardware.atrace@1.0-service.rc"
    "etc/vintf/manifest/android.hardware.atrace@1.0-service.xml"
    "bin/hw/android.hardware.drm@1.3-service.clearkey"
    "bin/hw/android.hardware.drm@1.4-service.clearkey"
    "bin/hw/android.hardware.health@2.1-service"
    "etc/init/android.hardware.health@2.1-service.rc"
    "etc/init/android.hardware.drm@1.4-service.clearkey.rc"
    "etc/vintf/manifest/android.hardware.health@2.1.xml"
    "etc/vintf/manifest/manifest_android.hardware.drm@1.4-service.clearkey.xml"
    "lib/hw/android.hardware.health@2.0-impl-2.1-qti.so"
    "lib64/hw/android.hardware.health@2.0-impl-2.1-qti.so"
    "lib/mediacas/libclearkeycasplugin.so"
    "lib64/mediacas/libclearkeycasplugin.so"
    "lib/mediadrm/libdrmclearkeyplugin.so"
    "lib64/mediadrm/libdrmclearkeyplugin.so"
    "bin/netutild"
    "etc/init/netutild.rc"
    "bin/hw/vendor.asus.wifi.netutil@1.1-service"
    "etc/init/vendor.asus.wifi.netutil@1.1-service.rc"
    "lib64/vendor.asus.wifi.netutil@1.1.so"
    "bin/hw/vendor.ims.glovemode@1.0-service"
    "etc/init/vendor.ims.glovemode@1.0-service.rc"
    "lib64/vendor.ims.glovemode@1.0.so"
    "bin/hw/vendor.ims.zenmotion@1.0-service"
    "etc/init/vendor.ims.zenmotion@1.0-service.rc"
    "lib64/vendor.ims.zenmotion@1.0.so"
    "bin/hw/vendor.ims.airtrigger@1.2-service"
    "etc/init/vendor.ims.airtrigger@1.2-service.rc"
    "lib64/vendor.ims.airtrigger@1.0.so"
    "lib64/vendor.ims.airtrigger@1.1.so"
    "lib64/vendor.ims.airtrigger@1.2.so"
    "bin/hw/vendor.ims.twinviewdock@1.0-service"
    "etc/init/vendor.ims.twinviewdock@1.0-service.rc"
    "lib64/vendor.ims.twinviewdock@1.0.so"
    "bin/hw/vendor.ims.wifiantennamode@1.0-service"
    "etc/init/vendor.ims.wifiantennamode@1.0-service.rc"
    "lib64/vendor.ims.wifiantennamode@1.0.so"
    "etc/init/vendor_flash_recovery.rc"
    "etc/init/vndservicemanager.rc"
    "bin/vndservice"
    "bin/vndservicemanager"
    "lib/libhwbinder.so"
    "lib64/libhwbinder.so"
    "lib/libavservices_minijail.so"
    "lib64/libavservices_minijail.so"
    "lib64/libavservices_minijail_vendor.so"
    "etc/init/boringssl_self_test.rc"
    "bin/hw/android.hardware.media.omx@1.0-service"
    "etc/init/android.hardware.media.omx@1.0-service.rc"
    "bin/hw/android.hardware.memtrack@1.0-service"
    "etc/init/android.hardware.memtrack@1.0-service.rc"
    "lib/hw/android.hardware.memtrack@1.0-impl.so"
    #"lib/hw/memtrack.default.so"
    "lib64/hw/android.hardware.memtrack@1.0-impl.so"
    #"lib64/hw/memtrack.default.so"
    "bin/hw/vendor.asus.wifi.rttutil@1.0-service"
    "bin/hw/vendor.ims.asusgeneralhidl@1.0-service"
    "etc/init/vendor.asus.wifi.rttutil@1.0-service.rc"
    "etc/init/vendor.ims.asusgeneralhidl@1.0-service.rc"
    "lib64/vendor.ims.asusgeneralhidl@1.0.so"
    "lib64/vendor.asus.wifi.netutil@1.0.so"
    "lib64/vendor.asus.wifi.rttutil@1.0.so"
    "lib/libgui_vendor.so"
    "lib64/libgui_vendor.so"
    "lib/android.frameworks.cameraservice.common@2.0.so"
    "lib/android.frameworks.cameraservice.device@2.0.so"
    "lib/android.frameworks.cameraservice.device@2.1.so"
    "lib/android.frameworks.cameraservice.service@2.0.so"
    "lib/android.frameworks.cameraservice.service@2.1.so"
    "lib/android.frameworks.cameraservice.service@2.2.so"
    "lib/android.frameworks.sensorservice@1.0.so"
    "lib64/android.frameworks.cameraservice.common@2.0.so"
    "lib64/android.frameworks.cameraservice.device@2.0.so"
    "lib64/android.frameworks.cameraservice.device@2.1.so"
    "lib64/android.frameworks.cameraservice.service@2.0.so"
    "lib64/android.frameworks.cameraservice.service@2.1.so"
    "lib64/android.frameworks.cameraservice.service@2.2.so"
    "lib64/android.frameworks.sensorservice@1.0.so"

    # Overlays
    "overlay/FrameworksResTarget.apk"
    "overlay/TeleServResOverlayOdm.apk"
    "overlay/WifiResTarget.apk"
    "overlay/aptxalsOverlay.apk"
    "overlay/FrameworksResTarget_Vendor.apk"
    "overlay/WifiResTarget_spf.apk"

    # Ozo processing
    "bin/hw/vendor.ozoaudio.media.c2@1.0-service"
    "bin/hw/vendor.ozoaudio.notify@1.0-service"
    "etc/ozosdk.license"
    "etc/init/ozonotify-1.0-service.rc"
    "etc/init/vendor.ozoaudio.media.c2@1.0-service.rc"
    "etc/seccomp_policy/vendor.ozoaudio.media.c2@1.0-default-seccomp_policy"
    "etc/vintf/manifest/ozonotify-1.0.xml"
    "lib/soundfx/libozoprocessing.so"
    "lib64/soundfx/libozoprocessing.so"
    "lib64/libav_ozodecoder.so"
    "lib/libav_ozoencoder.so"
    "lib64/libav_ozoencoder.so"
    "lib64/libcodec2_soft_ozodec.so"
    "lib64/libcodec2_soft_ozoenc.so"
    "lib/libozoaudio.so"
    "lib64/libozoaudio.so"
    "lib64/libozoc2store.so"
    "lib64/libozowidening.so"
    "lib/com.android.ozoaudio.notify@1.0.so"
    "lib64/com.android.ozoaudio.notify@1.0.so"
    "lib/libozoaudioutils.so"
    "lib/libozocapability.so"
    "lib64/libozoaudioutils.so"
    "lib64/libozocapability.so"

    # Permissions
    "etc/permissions/handheld_core_hardware.xml"

    # Power
    "bin/hw/android.hardware.power-service"
    "etc/init/android.hardware.power-service.rc"
    "etc/vintf/manifest/power.xml"
    "lib/android.hardware.power@1.0.so"
    "lib/android.hardware.power@1.1.so"
    "lib/android.hardware.power@1.2.so"
    "lib/hw/power.default.so"
    "lib64/hw/power.default.so"
    "lib64/android.hardware.power-V1-ndk_platform.so"
    "lib64/android.hardware.power@1.0.so"
    "lib64/android.hardware.power@1.1.so"
    "lib64/android.hardware.power@1.2.so"

    # Rfs
    "rfs/apq/gnss/hlos"
    "rfs/apq/gnss/ramdumps"
    "rfs/apq/gnss/readonly/firmware"
    "rfs/apq/gnss/readonly/vendor/firmware"
    "rfs/apq/gnss/readwrite"
    "rfs/apq/gnss/shared"
    "rfs/mdm/adsp/hlos"
    "rfs/mdm/adsp/ramdumps"
    "rfs/mdm/adsp/readonly/firmware"
    "rfs/mdm/adsp/readonly/vendor/firmware"
    "rfs/mdm/adsp/readwrite"
    "rfs/mdm/adsp/shared"
    "rfs/mdm/cdsp/hlos"
    "rfs/mdm/cdsp/ramdumps"
    "rfs/mdm/cdsp/readonly/firmware"
    "rfs/mdm/cdsp/readwrite"
    "rfs/mdm/cdsp/shared"
    "rfs/mdm/mpss/hlos"
    "rfs/mdm/mpss/ramdumps"
    "rfs/mdm/mpss/readonly/firmware"
    "rfs/mdm/mpss/readonly/vendor/firmware"
    "rfs/mdm/mpss/readwrite"
    "rfs/mdm/mpss/shared"
    "rfs/mdm/slpi/hlos"
    "rfs/mdm/slpi/ramdumps"
    "rfs/mdm/slpi/readonly/firmware"
    "rfs/mdm/slpi/readwrite"
    "rfs/mdm/slpi/shared"
    "rfs/mdm/tn/hlos"
    "rfs/mdm/tn/ramdumps"
    "rfs/mdm/tn/readonly/firmware"
    "rfs/mdm/tn/readwrite"
    "rfs/mdm/tn/shared"
    "rfs/msm/adsp/hlos"
    "rfs/msm/adsp/ramdumps"
    "rfs/msm/adsp/readonly/firmware"
    "rfs/msm/adsp/readonly/vendor/firmware"
    "rfs/msm/adsp/readwrite"
    "rfs/msm/adsp/shared"
    "rfs/msm/cdsp/hlos"
    "rfs/msm/cdsp/ramdumps"
    "rfs/msm/cdsp/readonly/firmware"
    "rfs/msm/cdsp/readonly/vendor/firmware"
    "rfs/msm/cdsp/readwrite"
    "rfs/msm/cdsp/shared"
    "rfs/msm/mpss/hlos"
    "rfs/msm/mpss/ramdumps"
    "rfs/msm/mpss/readonly/firmware"
    "rfs/msm/mpss/readonly/vendor/firmware"
    "rfs/msm/mpss/readwrite"
    "rfs/msm/mpss/shared"
    "rfs/msm/slpi/hlos"
    "rfs/msm/slpi/ramdumps"
    "rfs/msm/slpi/readonly/firmware"
    "rfs/msm/slpi/readonly/vendor/firmware"
    "rfs/msm/slpi/readwrite"
    "rfs/msm/slpi/shared"
    "rfs/mdm/cdsp/readonly/vendor/firmware"
    "rfs/mdm/slpi/readonly/vendor/firmware"
    "rfs/mdm/tn/readonly/vendor/firmware"
    "rfs/mdm/wpss/hlos"
    "rfs/mdm/wpss/ramdumps"
    "rfs/mdm/wpss/readonly/firmware"
    "rfs/mdm/wpss/readonly/vendor/firmware"
    "rfs/mdm/wpss/readwrite"
    "rfs/mdm/wpss/shared"
    "rfs/msm/wpss/hlos"
    "rfs/msm/wpss/ramdumps"
    "rfs/msm/wpss/readonly/firmware"
    "rfs/msm/wpss/readonly/vendor/firmware"
    "rfs/msm/wpss/readwrite"
    "rfs/msm/wpss/shared"
    "rfs/rfs_symlinks"

    # Sepolicy
    "etc/selinux/vendor_file_contexts"
    "etc/selinux/vendor_service_contexts"
    "etc/selinux/plat_sepolicy_vers.txt"
    "etc/selinux/vndservice_contexts"
    "etc/selinux/plat_pub_versioned.cil"
    "etc/selinux/vendor_hwservice_contexts"
    "etc/selinux/vendor_mac_permissions.xml"
    "etc/selinux/vendor_property_contexts"
    "etc/selinux/vendor_seapp_contexts"
    "etc/selinux/vendor_sepolicy.cil"
    "etc/selinux/selinux_denial_metadata"

    # Sla
    "bin/hw/vendor.qti.sla.service@1.0-service"
    "bin/slad-v2"
    "etc/init/slad-v2.rc"
    "etc/init/vendor.qti.sla.service@1.0-service.rc"
    "etc/sla/slad.conf"
    "etc/sla/slmAppUseCase.conf"
    "etc/sla/slm_supported_list.xml"
    "lib/hw/vendor.qti.sla.service@1.0-impl.so"
    "lib64/hw/vendor.qti.sla.service@1.0-impl.so"
    "lib/vendor.qti.sla.service@1.0.so"
    "lib64/vendor.qti.sla.service@1.0.so"

    # Symlink
    "factory"
    "odm"

    # Ueventd
    "ueventd.rc"

    # Usb
    "bin/init.qcom.usb.sh"
    "bin/hw/android.hardware.usb.gadget@1.1-service-qti"
    "bin/hw/android.hardware.usb@1.2-service-qti"
    "etc/init/hw/init.qcom.usb.rc"
    "etc/usb_compositions.conf"
    "etc/init/android.hardware.usb.gadget@1.1-service-qti.rc"
    "etc/init/android.hardware.usb@1.2-service-qti.rc"
    "etc/vintf/manifest/android.hardware.usb.gadget@1.1-service.xml"
    "etc/vintf/manifest/android.hardware.usb@1.2-service.xml"
    "lib64/android.hardware.usb.gadget@1.0.so"
    "lib64/android.hardware.usb.gadget@1.1.so"
    "lib64/android.hardware.usb@1.0.so"
    "lib64/android.hardware.usb@1.1.so"
    "lib64/android.hardware.usb@1.2.so"

    # Vibrator
    "bin/hw/vendor.asus.vibrator.vibratorgovern@1.0-service"
    "etc/init/vendor.asus.vibrator.vibratorgovern@1.0-service.rc"
    "lib/vendor.asus.vibrator.vibratorgovern@1.0.so"
    "lib64/vendor.asus.vibrator.vibratorgovern@1.0.so"
    "lib/hw/vendor.asus.vibrator.vibratorgovern@1.0-impl.so"
    "lib64/hw/vendor.asus.vibrator.vibratorgovern@1.0-impl.so"
    "bin/hw/vendor.qti.hardware.vibrator.service"
    "etc/init/init.aw8697.rc"
    "etc/init/vendor.qti.hardware.vibrator.service.rc"
    "etc/vintf/manifest/vendor.qti.hardware.vibrator.service.xml"
    "lib64/vendor.qti.hardware.vibrator.impl.so"
    "lib64/libqtivibratoreffect.so"
    "lib/hw/vibrator.default.so"
    "lib64/hw/vibrator.default.so"
    "lib/libvibrator.so"
    "lib64/libvibrator.so"

    # Wifi
    "bin/hw/android.hardware.wifi@1.0-service"
    "etc/init/android.hardware.wifi@1.0-service.rc"
    "etc/vintf/manifest/android.hardware.wifi@1.0-service.xml"
    "bin/wifistresstest.sh"
    "etc/init/vendor.qti.hardware.wifi.wifilearner@1.0-service.rc"
    "lib64/vendor.qti.hardware.wifi.wifilearner@1.0.so"
    "etc/vintf/manifest/android.hardware.wifi.hostapd.xml"
    "lib64/vendor.asus.wifi.hostapd@1.0.so"
    "bin/hostapd_cli"
    "bin/hw/hostapd"
    "etc/hostapd/hostapd.accept"
    "etc/hostapd/hostapd.deny"
    "etc/hostapd/hostapd_default.conf"
    "etc/init/hostapd.android.rc"
    "etc/wifi/qca6390/WCNSS_qcom_cfg.ini"
    "etc/wifi/qca6750/WCNSS_qcom_cfg.ini"
    "bin/fstman"
    "etc/init/vendor.qti.hardware.fstman@1.0-service.rc"
    "etc/wifi/fstman.ini"
    "lib64/vendor.qti.hardware.fstman@1.0.so"
    "etc/wifi/aoa_cldb_falcon.bin"
    "etc/wifi/aoa_cldb_swl14.bin"
    "etc/wifi/icm.conf"
    "bin/qsh_wifi_test"
    "bin/wifilearner"
    "bin/hw/wpa_supplicant"
    "etc/init/android.hardware.wifi.supplicant-service.rc"
    "lib64/libkeystore-engine-wifi-hidl.so"
    "lib64/libkeystore-wifi-hidl.so"
    "lib/libwifi-hal-ctrl.so"
    "lib/libwifi-hal-qcom.so"
    "lib/libwpa_client.so"
    "lib64/libwpa_client.so"
    "lib64/libwifi-hal.so"
    "lib64/libwifi-hal-ctrl.so"
    "lib64/libwifi-hal-qcom.so"
    "lib/libxtwifi_server_protocol.so"
    "lib/libxtwifi_server_protocol_uri_v3.so"
    "lib64/libxtwifi_server_protocol.so"
    "lib64/libxtwifi_server_protocol_uri_v3.so"
    "bin/rttutild"
    "etc/init/rttutild.rc"

    # WifiDisplay
    "bin/wfdhdcphalservice"
    "bin/wfdvndservice"
    "bin/wifidisplayhalservice"
    "etc/init/android.hardware.drm@1.1-service.wfdhdcp.rc"
    "etc/init/com.qualcomm.qti.wifidisplayhal@1.0-service.rc"
    "etc/init/wfdvndservice.rc"
    "etc/seccomp_policy/wfdhdcphalservice.policy"
    "etc/seccomp_policy/wfdvndservice.policy"
    "etc/seccomp_policy/wifidisplayhalservice.policy"
    "etc/ArmHDCP_QTI_Android.cfg"
    "etc/ArmHDCP_QTI_Android_8450.cfg"
    "etc/wfdconfig.xml"
    "etc/wfdconfig_720.xml"
    "etc/wfdconfig_MI.xml"
    "lib/libDxHdcp.so"
    "lib/libmm-hdcpmgr.so"
    "lib64/libDxHdcp.so"
    "lib64/libFileMux_proprietary.so"
    "lib64/libmm-hdcpmgr.so"
    "lib64/libmmosal_vendor.so"
    "lib64/libmmrtpdecoder_vendor.so"
    "lib64/libmmrtpencoder_vendor.so"
    "lib64/libwfdaac_vendor.so"
    "lib64/libwfdcodecv4l2_proprietary.so"
    "lib64/libwfdcommonutils_proprietary.so"
    "lib64/libwfdconfigutils_proprietary.so"
    "lib64/libwfddisplayconfig_vendor.so"
    "lib64/libwfdhdcpcp.so"
    "lib64/libwfdhdcpservice_proprietary.so"
    "lib64/libwfdmminterface_proprietary.so"
    "lib64/libwfdmmservice_proprietary.so"
    "lib64/libwfdmmsrc_proprietary.so"
    "lib64/libwfdmodulehdcpsession.so"
    "lib64/libwfdrtsp_vendor.so"
    "lib64/libwfdsessionmodule.so"
    "lib64/libwfdsourcesession_proprietary.so"
    "lib64/libwfdsourcesm_proprietary.so"
    "lib64/libwfduibcinterface_vendor.so"
    "lib64/libwfduibcsink_vendor.so"
    "lib64/libwfduibcsinkinterface_vendor.so"
    "lib64/libwfduibcsrc_vendor.so"
    "lib64/libwfduibcsrcinterface_vendor.so"
    "lib64/libwfdutils_proprietary.so"
    "lib64/vendor.qti.hardware.wifidisplaysession@1.0.so"
    "lib64/vendor.qti.hardware.wifidisplaysessionl@1.0-halimpl.so"
    "lib64/hw/vendor.qti.hardware.wifidisplaysession@1.0-impl.so"
)
ALL_SKIP_FILES=("${VENDOR_SKIP_FILES_COMMON[@]}" "${VENDOR_SKIP_FILES_DEVICE[@]}")

generate_prop_list_from_image "$1" "$2" ALL_SKIP_FILES

# Fixups
_output_file=$2
function presign() {
    sed -i "s|vendor/$1$|vendor/$1;PRESIGNED|g" $_output_file
}
function as_module() {
    sed -i "s|vendor/$1$|-vendor/$1|g" $_output_file
}
function add_on() {
    sed -i "s|vendor/$1$|vendor/$1:vendor_dlkm/$1|g" $_output_file
}

as_module "etc/vintf/manifest/android.hardware.gnss@2.1-service-qti.xml"
as_module "etc/vintf/manifest/android.hardware.thermal@2.0-service.qti.xml"
as_module "etc/vintf/manifest/android.hardware.usb@1.2-service.xml"
as_module "etc/vintf/manifest/c2_manifest_vendor.xml"
as_module "etc/vintf/manifest/vendor.qti.diag.hal.service.xml"
as_module "etc/vintf/manifest/vendor.qti.hardware.servicetracker@1.2-service.xml"
as_module "etc/vintf/manifest/android.hardware.gnss-aidl-service-qti.xml"
as_module "etc/vintf/manifest/android.hardware.neuralnetworks-shim-service-qti.xml"
as_module "etc/vintf/manifest/android.hardware.security.keymint-service-qti.xml"
as_module "etc/vintf/manifest/android.hardware.sensors@2.1-multihal.xml"
as_module "etc/vintf/manifest/android.hardware.usb.gadget@1.1-service.xml"
as_module "etc/vintf/manifest/android.hardware.wifi.supplicant.xml"
as_module "etc/vintf/manifest/c2_manifest_vendor_audio.xml"
as_module "etc/vintf/manifest/dataconnection-saidl.xml"
as_module "etc/vintf/manifest/manifest_android.hardware.drm@1.4-service.widevine.xml"
as_module "etc/vintf/manifest/manifest_lahaina_identity.xml"
as_module "etc/vintf/manifest/manifest_non_qmaa.xml"
as_module "etc/vintf/manifest/manifest_non_qmaa_extn.xml"
as_module "etc/vintf/manifest/memtrack_qti.xml"
as_module "etc/vintf/manifest/ozonotify-1.0.xml"
as_module "etc/vintf/manifest/qtiradio-saidl.xml"
as_module "etc/vintf/manifest/vendor.qti.gnss-service.xml"
as_module "etc/vintf/manifest/vendor.qti.hardware.limits-service.xml"
as_module "etc/vintf/manifest/vendor.qti.hardware.perf.xml"
as_module "etc/vintf/manifest/vendor.qti.hardware.power.powermodule.xml"
as_module "etc/vintf/manifest/vendor.qti.hardware.qconfig@1.0-service.xml"
as_module "etc/vintf/manifest/vendor.qti.hardware.qxr-service.xml"
as_module "etc/vintf/manifest/vendor.qti.hardware.radio.ims.xml"
as_module "etc/vintf/manifest/vendor.qti.hardware.vpp@2.0-service.xml"
as_module "etc/vintf/manifest/vendor.qti.hardware.wifi.wificfr@1.0-service.xml"
